### ISSUE TITLE
win平台报错

### ISSUE THREAD

**Issue by shen-lan** [answershuto/H5#6]
`
C:\Users\Administrator\Desktop\H5Model\H5-master\H5-master>npm  start

> html5@1.0.0 start C:\Users\Administrator\Desktop\H5Model\H5-master\H5-ma
> babel-node bin/www

`open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or
e `useMongoClient` option if using `connect()` or `createConnection()`. Se
://mongoosejs.com/docs/connections.html#use-mongo-client
init express..
app started,listen on port: 3000

events.js:141
      throw er; // Unhandled 'error' event
      ^
`

**Comment by answershuto** [comment]
@shen-lan Hi,what is the version of mongo?

**Comment by shen-lan** [comment]
我还以为直接node跑起来就OK，还要MogoDB？

**Comment by answershuto** [comment]
@shen-lan 对的，README里面我没写要装Mongo，不过我写了用到了，我去补充一下。

**Comment by shen-lan** [comment]
直接npm install安装完毕后，貌似没有Mongo。只有mongoose。我要手动再install Mongo?

**Comment by answershuto** [comment]
@shen-lan 这个是mongoose模块用来操作数据库的，你要在你电脑上安装配置好Mongo数据库。
